apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - vote-deployment-patch.yaml
  - vote-service-patch.yaml
  - result-service-patch.yaml
namespace: dev
